Repository Beacon-2023/Beacon-backend, pull requests merged in 2023-08, with the labels that each got.

#20 Feat: Swagger 추가
  build.gradle
  src/main/java/com/BEACON/beacon/global/config/swagger/OpenApiConfig.java
  src/main/resources/application.yml
Labels: enhancement

#21 Feat: 회원가입 구현
  build.gradle
  src/main/java/com/BEACON/beacon/domain/user/dao/MemberRepository.java
  src/main/java/com/BEACON/beacon/domain/user/domain/Member.java
  src/main/java/com/BEACON/beacon/global/BaseTimeEntity.java
  src/main/java/com/BEACON/beacon/global/HttpStatusResponse.java
  src/main/java/com/BEACON/beacon/global/config/JpaAuditingConfig.java
  src/main/java/com/BEACON/beacon/global/config/security/SecurityConfig.java
  src/main/java/com/BEACON/beacon/member/MemberStatus.java
  src/main/java/com/BEACON/beacon/member/controller/MemberController.java
  src/main/java/com/BEACON/beacon/member/dao/MemberRepository.java
  src/main/java/com/BEACON/beacon/member/domain/MemberEntity.java
  src/main/java/com/BEACON/beacon/member/dto/MemberDto.java
  src/main/java/com/BEACON/beacon/member/service/MemberService.java
  src/test/java/com/BEACON/beacon/domain/MemberRepositoryTest.java
  src/test/java/com/BEACON/beacon/member/controller/MemberControllerTest.java
  src/test/java/com/BEACON/beacon/member/integration/MemberServiceIntegrationTest.java
  src/test/java/com/BEACON/beacon/member/service/MemberServiceTest.java
Labels: enhancement

#43 Refactor: 회원부분 수정
  .gitignore
  build.gradle
  src/main/java/com/BEACON/beacon/fcm/FcmMessage.java
  src/main/java/com/BEACON/beacon/fcm/UserType.java
  src/main/java/com/BEACON/beacon/fcm/controller/FcmTokenController.java
  src/main/java/com/BEACON/beacon/fcm/dao/FcmTokenRepository.java
  src/main/java/com/BEACON/beacon/fcm/domain/FcmTokenEntity.java
  src/main/java/com/BEACON/beacon/fcm/dto/FcmTokenDto.java
  src/main/java/com/BEACON/beacon/fcm/mapper/FcmTokenMapper.java
  src/main/java/com/BEACON/beacon/fcm/service/FcmTokenService.java
  src/main/java/com/BEACON/beacon/fcm/service/FirebaseCloudMessageService.java
  src/main/java/com/BEACON/beacon/member/controller/MemberController.java
  src/main/java/com/BEACON/beacon/member/dao/MemberRepository.java
  src/main/java/com/BEACON/beacon/member/domain/MemberEntity.java
  src/main/java/com/BEACON/beacon/member/dto/MemberDto.java
  src/main/java/com/BEACON/beacon/member/dto/SessionDto.java
  src/main/java/com/BEACON/beacon/member/mapper/MemberMapper.java
  src/main/java/com/BEACON/beacon/member/request/MemberLoginRequestDto.java
  src/main/java/com/BEACON/beacon/member/service/MemberService.java
  src/main/java/com/BEACON/beacon/member/service/SessionLoginService.java
  src/test/java/com/BEACON/beacon/member/controller/MemberControllerTest.java
  src/test/java/com/BEACON/beacon/member/integration/MemberServiceIntegrationTest.java
  src/test/java/com/BEACON/beacon/member/service/MemberServiceTest.java
Labels: refactor

#49 Docs: readme 문서 수정
  README.md
Labels: chore

#47 Feat: 위치API 구현
  .gitignore
  build.gradle
  src/main/java/com/BEACON/beacon/global/HttpStatusResponse.java
  src/main/java/com/BEACON/beacon/global/error/exception/LegalDongCodeNotFoundException.java
  src/main/java/com/BEACON/beacon/location/controller/LocationController.java
  src/main/java/com/BEACON/beacon/location/dao/RegionTokenRepository.java
  src/main/java/com/BEACON/beacon/location/domain/RegionTokenEntity.java
  src/main/java/com/BEACON/beacon/location/dto/LocationDto.java
  src/main/java/com/BEACON/beacon/location/response/KakaoApiResponse.java
  src/main/java/com/BEACON/beacon/location/response/KakaoDocument.java
  src/main/java/com/BEACON/beacon/location/response/KakaoMetaData.java
  src/main/java/com/BEACON/beacon/location/service/LocationApiService.java
  src/main/java/com/BEACON/beacon/member/controller/MemberController.java
  src/main/resources/application.yml
  src/test/java/com/BEACON/beacon/location/service/LocationApiServiceTest.java
Labels: enhancement

#50 Feat: 푸시알림 메소드 구현
  src/main/java/com/BEACON/beacon/fcm/service/FcmTokenService.java
  src/main/java/com/BEACON/beacon/location/service/LocationApiService.java
  src/main/java/com/BEACON/beacon/scraping/service/ScrapingService.java
  src/test/java/com/BEACON/beacon/fcm/service/FirebaseCloudMessageServiceTest.java
  src/test/java/com/BEACON/beacon/scraping/service/ScrapingServiceTest.java
Labels: enhancement

#53 Docs: Swagger 문서 정의
  src/main/java/com/BEACON/beacon/fcm/controller/FcmTokenController.java
  src/main/java/com/BEACON/beacon/fcm/dto/FcmTokenDto.java
  src/main/java/com/BEACON/beacon/location/controller/LocationController.java
  src/main/java/com/BEACON/beacon/location/dto/LocationDto.java
  src/main/java/com/BEACON/beacon/member/controller/MemberController.java
  src/main/java/com/BEACON/beacon/member/dto/MemberDto.java
  src/main/java/com/BEACON/beacon/member/request/MemberLoginRequestDto.java
Labels: documentation
